// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYPBBJBboOyvEfrAzUeCg2OrLEjbxWmZQ',
    appId: '1:332527150538:web:d17569840984aa31c69b33',
    messagingSenderId: '332527150538',
    projectId: 'musculo-2ba15',
    authDomain: 'musculo-2ba15.firebaseapp.com',
    storageBucket: 'musculo-2ba15.appspot.com',
    measurementId: 'G-NXQSX680H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA249FEmCf6hi2iTap26BZjyc3GmiDHjz0',
    appId: '1:332527150538:android:eaf73791fa10b1f4c69b33',
    messagingSenderId: '332527150538',
    projectId: 'musculo-2ba15',
    storageBucket: 'musculo-2ba15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkciz0xGfJQN0GsPmj5yAXAEtW2GUWbvs',
    appId: '1:332527150538:ios:aa406e6c57e6719ac69b33',
    messagingSenderId: '332527150538',
    projectId: 'musculo-2ba15',
    storageBucket: 'musculo-2ba15.appspot.com',
    androidClientId:
        '332527150538-kh4am4skcvd8ejg17heb5r8npkl76b0j.apps.googleusercontent.com',
    iosClientId:
        '332527150538-8ropr5fh8kmbb87v6go6obihemasun9f.apps.googleusercontent.com',
    iosBundleId: 'com.dartsync.musculoApp',
  );
}
