const _assets = "assets/images";
const String _icons = "assets/icons";
const String _svgs = "assets/svgs";

class Assets {
  static const String editIcon = '$_icons/Edit.svg';
  static const String runnerIcon = "$_icons/runner.svg";
  static const String walletIcon = "$_icons/Wallet.svg";
  static const String timeCircle = "$_icons/Time Circle.svg";
  static const String hide = "$_icons/Hide.svg";
  static const String lock = "$_icons/Lock.svg";
  static const String message = "$_icons/Message.svg";
  static const String show = "$_icons/Show.svg";
  static const String male = "$_icons/male.svg"; // not used
  static const String female = "$_icons/female.svg";
  static const String filterIcon = "$_icons/Filter.svg";
  static const String searchIcon = "$_icons/Search.svg";
  static const String settingIcon = "$_icons/Setting.svg";
  static const String feedbackIcon = "$_icons/Danger Circle.svg";
  static const String feedbackIcon1 = "$_icons/Info Circle.svg";
  static const String homeIcon = "$_icons/Home.svg";
  static const String discoveryIcon = "$_icons/Discovery.svg";
  static const String discoveryIcon1 = "$_icons/Discovery1.svg";
  static const String profilIcon = "$_icons/Profile.svg";
  static const String profilIcon1 = "$_icons/Profile1.svg";
  static const String home1 = "$_icons/Home1.svg";
  static const String downArrow = "$_icons/ArrowDown 2.svg";
  static const String message1 = "$_icons/Message1.svg";
  static const String calendar1 = "$_icons/Calendar1.svg";
  static const String discovery2 = "$_icons/Discovery2.svg";
  static const String moreHrizontal = "$_icons/moreHorizontal.svg";
  static const String chart = "$_icons/Chart.svg";
  static const String daimond = "$_icons/diamond.svg";
  static const String editIcon1 = "$_icons/Edit1.svg";
  static const String plusIcon = "$_icons/Plusicon.png";
  static const String editBlack = "$_icons/EditBlack.svg";
  static const String chartBlack = "$_icons/ChartBlack.svg";
  static const String star1 = "$_icons/Star1.svg";
  static const String upload1 = "$_icons/Upload1.svg";
  static const String sqaure1 = "$_icons/Close Square1.png"; // not used
  static const String arrowUp = "$_icons/ArrowUp2.svg";
  static const String reportIcon = "$_icons/Shield Fail.svg";
  static const String deleteIcon = "$_icons/Delete.svg";
  static const String heartFill = "$_icons/Heart Fill.svg";

  static const String logo = '$_assets/applogo.png';
  static const String maskgroup = "$_assets/maskgroup.png";
  static const String monogram = "$_assets/monogram.png";
  static const String vector = "$_assets/Vector.png";
  static const String group = "$_assets/Group.png";
  static const String bgimage = "$_assets/bgimage.png";
  static const String man = "$_assets/man.png";
  static const String discovery = "$_assets/Discovery.png"; // not used
  static const String playbutton = "$_assets/PlayButton.png"; // not used
  static const String workout = "$_assets/workuot.png";
  static const String profilebgpng = "$_assets/profilebg.png";
  static const String gpayment = "$_assets/gpayment.png";
  static const String ellipse = "$_assets/Ellipse.png";
  static const String monog = "$_assets/monog.png"; // not used
  static const String whatsappimage = "$_assets/Mask Group.png";
  static const String twitterImage = "$_assets/twitterImage.png";
  static const String instagramImage = "$_assets/instagramImage.png";
  static const String bellyFat = "$_assets/belly Fat.png";
  static const String coachProfile = "$_assets/coachProfile.png";
  static const String rectanglework = "$_assets/Rectanglework.png";
  static const String profileDImage = "$_assets/profile_DImage.png";
  static const String crossIcon = "$_assets/cross icon.png";

  static const String facebook = "$_svgs/facebook.svg";
  static const String google = "$_svgs/google.svg";
  static const String apple = "$_svgs/apple.svg";
  static const String previous = "$_svgs/previous.svg";
  static const String next = "$_svgs/next.svg";
  static const String swap = "$_svgs/Swap.svg";
  static const String congrate = "$_svgs/cong.svg";
  static const String whatsapp = "$_svgs/whatsApp.svg"; // not used
  static const String twitter = "$_svgs/x.svg"; // not used
  static const String insta = "$_svgs/meta.svg"; // not used
  static const String official = "$_svgs/official.svg";
  static const String monugram = "$_svgs/monugram.svg"; // not used
  static const String addUser = "$_svgs/Add User.svg";
  static const String switchUser = "$_svgs/switch_user.svg";
  static const String notification = "$_svgs/Notification.svg";
  static const String condition = "$_svgs/condition.svg";
  static const String logout = "$_svgs/Logout.svg";
  static const String groupCircle = "$_svgs/Groupcircle.svg";
  static const String profileIcon = "$_svgs/Profile.svg";
  static const String heartIcon = "$_svgs/Heart.svg";
  static const String calendarIcon = "$_svgs/Calendar.svg";
  static const String documentIcon = "$_svgs/Document.svg";
  static const String empty = "$_svgs/empty.svg"; // used

  static const String profilebg = "$_svgs/profilebg.svg";
  static const String tWallet = "$_svgs/tWallet.svg";
  static const String downSquare = "$_svgs/Down Square.svg";
  static const String rdownSquare = "$_svgs/RDown Square.svg";
  static const String mailDraw = "$_svgs/mailDraw.svg";
  static const String arrowleft = "$_svgs/ArrowLeft.svg";
  static const String playbutt = "$_svgs/Play Button.svg";
  static const String dumbellImage = "$_svgs/dumbell.svg";
  static const String closeSquare = "$_svgs/Close Square.svg";
  static const String whatsappIcon = "$_svgs/whatsapp icon.svg";
  static const String eidtSquare = "$_svgs/Edit Square.svg";
}
